// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package attendance

import (
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"mceasy/ent"
	"mceasy/internal/applications/attendance/repository"
	"mceasy/internal/applications/attendance/service"
	"mceasy/internal/component/cache"
	"mceasy/internal/component/transaction"
)

// Injectors from attendance_injector.go:

func InitializedAttendanceService(dbClient *ent.Client, redisClient *redis.Client) *service.AttendanceServiceImpl {
	attendanceRepositoryImpl := repository.NewAttendanceRepository(dbClient)
	cacheImpl := cache.NewCache(redisClient)
	trxImpl := transaction.NewTrx(dbClient)
	attendanceServiceImpl := service.NewAttendanceService(attendanceRepositoryImpl, cacheImpl, trxImpl)
	return attendanceServiceImpl
}

// attendance_injector.go:

var providerAttendance = wire.NewSet(repository.NewAttendanceRepository, transaction.NewTrx, service.NewAttendanceService, cache.NewCache, wire.Bind(new(repository.AttendanceRepository), new(*repository.AttendanceRepositoryImpl)), wire.Bind(new(transaction.Trx), new(*transaction.TrxImpl)), wire.Bind(new(cache.Cache), new(*cache.CacheImpl)), wire.Bind(new(service.AttendanceService), new(*service.AttendanceServiceImpl)))
