// Code generated by mockery v2.23.0. DO NOT EDIT.

package mock_inbound

import (
	config "mceasy/internal/component/rabbitmq/config"

	mock "github.com/stretchr/testify/mock"
)

// Inbound is an autogenerated mock type for the Inbound type
type Inbound struct {
	mock.Mock
}

// GetMessage provides a mock function with given fields: cfg
func (_m *Inbound) GetMessage(cfg config.IRabbitMQConfig) (bool, error) {
	ret := _m.Called(cfg)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(config.IRabbitMQConfig) (bool, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(config.IRabbitMQConfig) bool); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(config.IRabbitMQConfig) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInbound interface {
	mock.TestingT
	Cleanup(func())
}

// NewInbound creates a new instance of Inbound. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInbound(t mockConstructorTestingTNewInbound) *Inbound {
	mock := &Inbound{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
