// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttendancesColumns holds the columns for the "attendances" table.
	AttendancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "attendance_date", Type: field.TypeTime},
		{Name: "check_in_time", Type: field.TypeTime, Nullable: true},
		{Name: "check_out_time", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"present", "absent", "late", "half_day"}, Default: "absent"},
		{Name: "is_weekend", Type: field.TypeBool, Default: false},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "marked_by_admin", Type: field.TypeBool, Default: false},
		{Name: "employee_id", Type: field.TypeUint64},
	}
	// AttendancesTable holds the schema information for the "attendances" table.
	AttendancesTable = &schema.Table{
		Name:       "attendances",
		Columns:    AttendancesColumns,
		PrimaryKey: []*schema.Column{AttendancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attendances_employees_attendances",
				Columns:    []*schema.Column{AttendancesColumns[11]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "attendance_employee_id_attendance_date",
				Unique:  true,
				Columns: []*schema.Column{AttendancesColumns[11], AttendancesColumns[4]},
			},
			{
				Name:    "attendance_attendance_date",
				Unique:  false,
				Columns: []*schema.Column{AttendancesColumns[4]},
			},
			{
				Name:    "attendance_employee_id",
				Unique:  false,
				Columns: []*schema.Column{AttendancesColumns[11]},
			},
			{
				Name:    "attendance_status",
				Unique:  false,
				Columns: []*schema.Column{AttendancesColumns[7]},
			},
			{
				Name:    "attendance_is_weekend",
				Unique:  false,
				Columns: []*schema.Column{AttendancesColumns[8]},
			},
		},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "employee_id", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "full_name", Type: field.TypeString, Size: 255},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "position", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "department", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "hire_date", Type: field.TypeTime},
		{Name: "base_salary", Type: field.TypeFloat64, Default: 1e+07},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:       "employees",
		Columns:    EmployeesColumns,
		PrimaryKey: []*schema.Column{EmployeesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "employee_employee_id",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[4]},
			},
			{
				Name:    "employee_email",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[6]},
			},
			{
				Name:    "employee_is_active",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[12]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "text", Type: field.TypeString},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RoleUsersColumns holds the columns for the "role_users" table.
	RoleUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUint64, Nullable: true},
		{Name: "role_id", Type: field.TypeUint64, Nullable: true},
	}
	// RoleUsersTable holds the schema information for the "role_users" table.
	RoleUsersTable = &schema.Table{
		Name:       "role_users",
		Columns:    RoleUsersColumns,
		PrimaryKey: []*schema.Column{RoleUsersColumns[0]},
	}
	// SalaryCalculationsColumns holds the columns for the "salary_calculations" table.
	SalaryCalculationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "calculation_month", Type: field.TypeTime},
		{Name: "base_salary", Type: field.TypeFloat64},
		{Name: "total_working_days", Type: field.TypeInt},
		{Name: "absent_days", Type: field.TypeInt, Default: 0},
		{Name: "present_days", Type: field.TypeInt, Default: 0},
		{Name: "final_salary", Type: field.TypeFloat64},
		{Name: "deduction_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "calculation_formula", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "employee_id", Type: field.TypeUint64},
	}
	// SalaryCalculationsTable holds the schema information for the "salary_calculations" table.
	SalaryCalculationsTable = &schema.Table{
		Name:       "salary_calculations",
		Columns:    SalaryCalculationsColumns,
		PrimaryKey: []*schema.Column{SalaryCalculationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "salary_calculations_employees_salary_calculations",
				Columns:    []*schema.Column{SalaryCalculationsColumns[12]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "salarycalculation_employee_id_calculation_month",
				Unique:  true,
				Columns: []*schema.Column{SalaryCalculationsColumns[12], SalaryCalculationsColumns[4]},
			},
			{
				Name:    "salarycalculation_calculation_month",
				Unique:  false,
				Columns: []*schema.Column{SalaryCalculationsColumns[4]},
			},
			{
				Name:    "salarycalculation_employee_id",
				Unique:  false,
				Columns: []*schema.Column{SalaryCalculationsColumns[12]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "fullname", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttendancesTable,
		EmployeesTable,
		RolesTable,
		RoleUsersTable,
		SalaryCalculationsTable,
		UsersTable,
	}
)

func init() {
	AttendancesTable.ForeignKeys[0].RefTable = EmployeesTable
	SalaryCalculationsTable.ForeignKeys[0].RefTable = EmployeesTable
}
