// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"mceasy/ent/employee"
	"mceasy/ent/predicate"
	"mceasy/ent/salarycalculation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SalaryCalculationQuery is the builder for querying SalaryCalculation entities.
type SalaryCalculationQuery struct {
	config
	ctx          *QueryContext
	order        []salarycalculation.OrderOption
	inters       []Interceptor
	predicates   []predicate.SalaryCalculation
	withEmployee *EmployeeQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SalaryCalculationQuery builder.
func (scq *SalaryCalculationQuery) Where(ps ...predicate.SalaryCalculation) *SalaryCalculationQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *SalaryCalculationQuery) Limit(limit int) *SalaryCalculationQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *SalaryCalculationQuery) Offset(offset int) *SalaryCalculationQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *SalaryCalculationQuery) Unique(unique bool) *SalaryCalculationQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *SalaryCalculationQuery) Order(o ...salarycalculation.OrderOption) *SalaryCalculationQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QueryEmployee chains the current query on the "employee" edge.
func (scq *SalaryCalculationQuery) QueryEmployee() *EmployeeQuery {
	query := (&EmployeeClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(salarycalculation.Table, salarycalculation.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, salarycalculation.EmployeeTable, salarycalculation.EmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SalaryCalculation entity from the query.
// Returns a *NotFoundError when no SalaryCalculation was found.
func (scq *SalaryCalculationQuery) First(ctx context.Context) (*SalaryCalculation, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{salarycalculation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SalaryCalculationQuery) FirstX(ctx context.Context) *SalaryCalculation {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SalaryCalculation ID from the query.
// Returns a *NotFoundError when no SalaryCalculation ID was found.
func (scq *SalaryCalculationQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{salarycalculation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SalaryCalculationQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SalaryCalculation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SalaryCalculation entity is found.
// Returns a *NotFoundError when no SalaryCalculation entities are found.
func (scq *SalaryCalculationQuery) Only(ctx context.Context) (*SalaryCalculation, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{salarycalculation.Label}
	default:
		return nil, &NotSingularError{salarycalculation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SalaryCalculationQuery) OnlyX(ctx context.Context) *SalaryCalculation {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SalaryCalculation ID in the query.
// Returns a *NotSingularError when more than one SalaryCalculation ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *SalaryCalculationQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{salarycalculation.Label}
	default:
		err = &NotSingularError{salarycalculation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SalaryCalculationQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SalaryCalculations.
func (scq *SalaryCalculationQuery) All(ctx context.Context) ([]*SalaryCalculation, error) {
	ctx = setContextOp(ctx, scq.ctx, "All")
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SalaryCalculation, *SalaryCalculationQuery]()
	return withInterceptors[[]*SalaryCalculation](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *SalaryCalculationQuery) AllX(ctx context.Context) []*SalaryCalculation {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SalaryCalculation IDs.
func (scq *SalaryCalculationQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, "IDs")
	if err = scq.Select(salarycalculation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SalaryCalculationQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SalaryCalculationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, "Count")
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*SalaryCalculationQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SalaryCalculationQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SalaryCalculationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, "Exist")
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SalaryCalculationQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SalaryCalculationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SalaryCalculationQuery) Clone() *SalaryCalculationQuery {
	if scq == nil {
		return nil
	}
	return &SalaryCalculationQuery{
		config:       scq.config,
		ctx:          scq.ctx.Clone(),
		order:        append([]salarycalculation.OrderOption{}, scq.order...),
		inters:       append([]Interceptor{}, scq.inters...),
		predicates:   append([]predicate.SalaryCalculation{}, scq.predicates...),
		withEmployee: scq.withEmployee.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// WithEmployee tells the query-builder to eager-load the nodes that are connected to
// the "employee" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *SalaryCalculationQuery) WithEmployee(opts ...func(*EmployeeQuery)) *SalaryCalculationQuery {
	query := (&EmployeeClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withEmployee = query
	return scq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SalaryCalculation.Query().
//		GroupBy(salarycalculation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *SalaryCalculationQuery) GroupBy(field string, fields ...string) *SalaryCalculationGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SalaryCalculationGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = salarycalculation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SalaryCalculation.Query().
//		Select(salarycalculation.FieldCreatedAt).
//		Scan(ctx, &v)
func (scq *SalaryCalculationQuery) Select(fields ...string) *SalaryCalculationSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &SalaryCalculationSelect{SalaryCalculationQuery: scq}
	sbuild.label = salarycalculation.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SalaryCalculationSelect configured with the given aggregations.
func (scq *SalaryCalculationQuery) Aggregate(fns ...AggregateFunc) *SalaryCalculationSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *SalaryCalculationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !salarycalculation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SalaryCalculationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SalaryCalculation, error) {
	var (
		nodes       = []*SalaryCalculation{}
		_spec       = scq.querySpec()
		loadedTypes = [1]bool{
			scq.withEmployee != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SalaryCalculation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SalaryCalculation{config: scq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(scq.modifiers) > 0 {
		_spec.Modifiers = scq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := scq.withEmployee; query != nil {
		if err := scq.loadEmployee(ctx, query, nodes, nil,
			func(n *SalaryCalculation, e *Employee) { n.Edges.Employee = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (scq *SalaryCalculationQuery) loadEmployee(ctx context.Context, query *EmployeeQuery, nodes []*SalaryCalculation, init func(*SalaryCalculation), assign func(*SalaryCalculation, *Employee)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SalaryCalculation)
	for i := range nodes {
		fk := nodes[i].EmployeeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(employee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "employee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (scq *SalaryCalculationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	if len(scq.modifiers) > 0 {
		_spec.Modifiers = scq.modifiers
	}
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SalaryCalculationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(salarycalculation.Table, salarycalculation.Columns, sqlgraph.NewFieldSpec(salarycalculation.FieldID, field.TypeUint64))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salarycalculation.FieldID)
		for i := range fields {
			if fields[i] != salarycalculation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if scq.withEmployee != nil {
			_spec.Node.AddColumnOnce(salarycalculation.FieldEmployeeID)
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *SalaryCalculationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(salarycalculation.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = salarycalculation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range scq.modifiers {
		m(selector)
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (scq *SalaryCalculationQuery) Modify(modifiers ...func(s *sql.Selector)) *SalaryCalculationSelect {
	scq.modifiers = append(scq.modifiers, modifiers...)
	return scq.Select()
}

// SalaryCalculationGroupBy is the group-by builder for SalaryCalculation entities.
type SalaryCalculationGroupBy struct {
	selector
	build *SalaryCalculationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SalaryCalculationGroupBy) Aggregate(fns ...AggregateFunc) *SalaryCalculationGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *SalaryCalculationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, "GroupBy")
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SalaryCalculationQuery, *SalaryCalculationGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *SalaryCalculationGroupBy) sqlScan(ctx context.Context, root *SalaryCalculationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SalaryCalculationSelect is the builder for selecting fields of SalaryCalculation entities.
type SalaryCalculationSelect struct {
	*SalaryCalculationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *SalaryCalculationSelect) Aggregate(fns ...AggregateFunc) *SalaryCalculationSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *SalaryCalculationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, "Select")
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SalaryCalculationQuery, *SalaryCalculationSelect](ctx, scs.SalaryCalculationQuery, scs, scs.inters, v)
}

func (scs *SalaryCalculationSelect) sqlScan(ctx context.Context, root *SalaryCalculationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (scs *SalaryCalculationSelect) Modify(modifiers ...func(s *sql.Selector)) *SalaryCalculationSelect {
	scs.modifiers = append(scs.modifiers, modifiers...)
	return scs
}
