// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mceasy/ent/predicate"
	"mceasy/ent/salarycalculation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SalaryCalculationDelete is the builder for deleting a SalaryCalculation entity.
type SalaryCalculationDelete struct {
	config
	hooks    []Hook
	mutation *SalaryCalculationMutation
}

// Where appends a list predicates to the SalaryCalculationDelete builder.
func (scd *SalaryCalculationDelete) Where(ps ...predicate.SalaryCalculation) *SalaryCalculationDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *SalaryCalculationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *SalaryCalculationDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *SalaryCalculationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(salarycalculation.Table, sqlgraph.NewFieldSpec(salarycalculation.FieldID, field.TypeUint64))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// SalaryCalculationDeleteOne is the builder for deleting a single SalaryCalculation entity.
type SalaryCalculationDeleteOne struct {
	scd *SalaryCalculationDelete
}

// Where appends a list predicates to the SalaryCalculationDelete builder.
func (scdo *SalaryCalculationDeleteOne) Where(ps ...predicate.SalaryCalculation) *SalaryCalculationDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *SalaryCalculationDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{salarycalculation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *SalaryCalculationDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
