// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package salary

import (
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"mceasy/ent"
	"mceasy/internal/applications/salary/repository"
	"mceasy/internal/applications/salary/service"
	"mceasy/internal/component/cache"
	"mceasy/internal/component/transaction"
)

// Injectors from salary_injector.go:

func InitializedSalaryService(dbClient *ent.Client, redisClient *redis.Client) *service.SalaryServiceImpl {
	salaryRepositoryImpl := repository.NewSalaryRepository(dbClient)
	cacheImpl := cache.NewCache(redisClient)
	trxImpl := transaction.NewTrx(dbClient)
	salaryServiceImpl := service.NewSalaryService(salaryRepositoryImpl, cacheImpl, trxImpl)
	return salaryServiceImpl
}

// salary_injector.go:

var providerSalary = wire.NewSet(repository.NewSalaryRepository, transaction.NewTrx, service.NewSalaryService, cache.NewCache, wire.Bind(new(repository.SalaryRepository), new(*repository.SalaryRepositoryImpl)), wire.Bind(new(transaction.Trx), new(*transaction.TrxImpl)), wire.Bind(new(cache.Cache), new(*cache.CacheImpl)), wire.Bind(new(service.SalaryService), new(*service.SalaryServiceImpl)))
