// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package health

import (
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"mceasy/ent"
	"mceasy/internal/applications/health/repository"
	"mceasy/internal/applications/health/service"
	"mceasy/internal/component/cache"
)

// Injectors from health_injector.go:

func InitializeHealthService(dbClient *ent.Client, cacheClient *redis.Client) *service.HealthServiceImpl {
	healthRepositoryImpl := repository.NewHealthRepository(dbClient)
	cacheImpl := cache.NewCache(cacheClient)
	healthServiceImpl := service.NewHealthService(healthRepositoryImpl, cacheImpl)
	return healthServiceImpl
}

// health_injector.go:

var providerSetHealth = wire.NewSet(repository.NewHealthRepository, service.NewHealthService, cache.NewCache, wire.Bind(new(repository.HealthRepository), new(*repository.HealthRepositoryImpl)), wire.Bind(new(service.HealthService), new(*service.HealthServiceImpl)), wire.Bind(new(cache.Cache), new(*cache.CacheImpl)))
