// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"mceasy/ent"
	"mceasy/internal/applications/user/repository"
	"mceasy/internal/applications/user/service"
	"mceasy/internal/component/cache"
	"mceasy/internal/component/transaction"
)

// Injectors from user_injector.go:

func InitializedUserService(dbClient *ent.Client, redisClient *redis.Client) *service.UserServiceImpl {
	userRepositoryImpl := repository.NewUserRepository(dbClient)
	trxImpl := transaction.NewTrx(dbClient)
	cacheImpl := cache.NewCache(redisClient)
	userServiceImpl := service.NewUserService(userRepositoryImpl, trxImpl, cacheImpl)
	return userServiceImpl
}

// user_injector.go:

var providerUser = wire.NewSet(repository.NewUserRepository, transaction.NewTrx, service.NewUserService, cache.NewCache, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), wire.Bind(new(transaction.Trx), new(*transaction.TrxImpl)), wire.Bind(new(cache.Cache), new(*cache.CacheImpl)), wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))
