// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attendance is the predicate function for attendance builders.
type Attendance func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleUser is the predicate function for roleuser builders.
type RoleUser func(*sql.Selector)

// SalaryCalculation is the predicate function for salarycalculation builders.
type SalaryCalculation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
